repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic==2.10.6"
        args: [ --config-file=pyproject.toml ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.6"
    hooks:
      - id: ruff
        args:
        - --config=pyproject.toml
        - --fix

